name: Clarive Apache Plugin
description: Apache plugin will allow you to interact with Apache HTTP Server through CLI.
version: 1.0
icon: https://github.com/clarive/cla-apache-plugin/public/icon/apache.svg
url: https://github.com/clarive/cla-apache-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-apache-plugin
